const CHARACTERS = {
  LOAD_DEFAULT: 'CHARACTERS_LOAD_DEFAULT',
  LOAD_SEARCH: 'CHARACTERS_SEARCH',
  LOAD_SUCCESS: 'CHARACTERS_LOAD_SUCCESS',
  LOAD_FAIL: 'CHARACTERS_LOAD_FAIL',
  PAGE: 'CHARACTERS_PAGE',
  LENGTH: 'CHARACTERS_LENGTH',
};
export { CHARACTERS };
